word = ['apple', 'banana', 'cherry']
print(word.index('cherry'))
print(word[-1])
print(word[0:2])
word.append("Sidharth")
print(word)
word.insert(1,"Amey")
print(word)
word.remove("apple")
print(word)
word.pop(2)
print(word)
word.sort()
print(word)
word.reverse()
print(word)
print(len(word))
