Name   = input("entre your name :- ")  
Age    = int(input("entre your age :- ") )
City   = input("entre your city :- ")
Height = float(input("entre your height :- "))

print("Hello, ",Name)
print("My age is ", Age ," years old.")
print("live in ",City)
print("Your height is", Height)
print("Next year you will be ",Age+1)
print(type(Name))
print(type(Age))
print(type(City))
print(type(Height))
